### ISSUE TITLE
Undefined Reference

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#100]
After the latest additions, I see the following error when building

CMakeFiles/ldmx-sim.dir/src/RunManager.cxx.o: In function `sim::RunManager::InitializePhysics()':
RunManager.cxx:(.text+0x268): undefined reference to `sim::GammaPhysics::GammaPhysics(G4String const&)'

**Comment by JeremyMcCormick** [comment]
The master is compiling fine for me.  I'm guessing you need to rerun cmake.

**Comment by omar-moreno** [comment]
Cloned a clean copy and it works now.
