### ISSUE TITLE
Scoring plane at front of ECal overlaps with ECal

### ISSUE THREAD

**Issue by aechavez** [LDMXAnalysis/ldmx-sw#1032]
**Describe the bug**
Taking a look at the constants.gdml (Lines 289-293 and line 304) and the scoring_planes.gdml (Line 27) for ldmx-det-v12, we can see that the ECal parent volume begins at z = 240.mm and the ECal itself begins 0.5mm away at z = 240.5mm. However, the z position of the scoring plane at the front of the ECal is z  = 240.5005mm, which implies that the scoring plane is defined by 240.5mm <= z <= 240.501mm. Therefore, the scoring plane at the front of the ECal overlaps with the ECal itself.

**Desired behavior**
We expect there to be no overlap between the scoring plane at the front of the ECal and the ECal itself.

**Comment by omar-moreno** [comment]
@aechavez Can you post a picture of the rendered detector? This will give us a better idea of how the overlaps look.

**Comment by aechavez** [comment]
I've attached several sketches of the detector that I put together in Math3D and Desmos. As you can see below, these are just some pictures of boxes that I have surrounding the target (Gray), trigger pads (Black), and ECal (Green).

<img width="1245" alt="Screen Shot 2021-11-10 at 10 07 30 PM" src="https://user-images.githubusercontent.com/57649078/141249131-b77c62fc-6dc5-4408-9419-b5986fc0def0.png">

Pictured below is the same image, first including the scoring plane at the front of the ECal, and then including the other ECal scoring planes.

<img width="1245" alt="Screen Shot 2021-11-10 at 10 07 53 PM" src="https://user-images.githubusercontent.com/57649078/141249546-51926046-cc78-46f2-9ff7-5140b769040c.png">
<img width="1245" alt="Screen Shot 2021-11-10 at 10 08 29 PM" src="https://user-images.githubusercontent.com/57649078/141249571-391ca07f-a1ab-4e87-92e7-ed4cad3fadba.png">

Things get cluttered pretty quickly, so I've also rendered the zy cross-section.

<img width="1160" alt="Screen Shot 2021-11-10 at 10 12 54 PM" src="https://user-images.githubusercontent.com/57649078/141249866-a30c4bfc-78eb-4156-957d-423542b98823.png">

Zooming into the upper right corner of the ECal box in the above image, you can see that the back and top scoring planes merely touch the ECal on one side. The same is also true of the bottom and side ECal scoring planes.

<img width="1160" alt="Screen Shot 2021-11-10 at 10 13 23 PM" src="https://user-images.githubusercontent.com/57649078/141250150-0cb89405-689b-4bde-a409-2e466bc6a40a.png">

However, the front ECal scoring plane is partially contained in the ECal as shown below.

<img width="1160" alt="Screen Shot 2021-11-10 at 10 16 29 PM" src="https://user-images.githubusercontent.com/57649078/141250363-9c27becd-726a-44fc-bd64-50f6dd170a5d.png">

**Comment by aechavez** [comment]
There are two other related items that I think I should mention here:

1. When I first brought this up, Joe mentioned that it might be better if the front ECal scoring plane were set closer to the first silicon layer. The reason is that for the BDT studies we have been using the position/momentum of the incoming electron at the front ECal scoring plane to make a projection of its trajectory. If the scoring plane is set further upstream, and there is some material between it and the first sensing layer, then we could run into a situation where an incoming electron that appears to be on a trajectory to produce a signal in the ECal is actually deflected away and does not produce a signal. So if possible we might want to consider moving the scoring plane further downstream, rather than further upstream.

2. There are some inconsistencies in the comments included in the constants.gdml for ldmx-det-v12. Whether or not these are indicative of another problem or they are just simple typos is something I think might be worth clarifying. In line 236, we have a comment that suggests layer B thickness is set to 22.35mm. However, actually carrying out the calculation in lines 238-242 results in a layer B thickness of 23.35mm, off by 1mm. This then gets carried over to the ECal_dz, which comes out to 450.2mm instead of the 449.2mm suggested by the comment in line 266. There's also one more, which I think is obviously a typo, and that's in lines 290-291 which have a comment saying that the ECal starts at 220.5mm while it clearly starts at 240.5mm.
