### ISSUE TITLE
Python bindings for DetectorIDs

### ISSUE THREAD

**Issue by EinarElen** [LDMXAnalysis/ldmx-sw#1048]
We discussed getting access to the various DetectorID classes from python with Boost.Python. I've been trying things out and I think the following is what would be needed 

- Updating the container to compile Boost.Python properly https://github.com/LDMX-Software/docker/issues/41
- Adding some `find_package` components in the CMakeLists.txt for DetDescr 
- Add a source + header file that defines the bindings that we want
- Add `${LDMX_SW_INSTALL}/lib` to the `${PYTHONPATH} environment variable 
In principle, you could actually just use a source file but that looks a bit weird. 

Doing so means that the `libDetDescr.so` shared object becomes consumable by python and you can import it with 
```python
import libDetDescr
# or 
from libDetDescr import HcalD # etc
``` 

The name of the python module has to be the same as the name of the shared object. If you wanted things to be a bit neater, you could add a separate library just for this but I don't think its worth it. 

For the various ID classes, my approach has been the following
- Export any base classes as objects only. This is the minimum required to use the derived classes. Is there a reason to export any functionality for e.g. `DetectorID`? If so, we could its just some additional boilerplate 
- For the derived classes export
  - The constructor from N pieces 
  - The constructor from a raw integer 
  - Accessor functions for the fields (in snake_case seems more pythonesque than the get* options) 
  - Any helper functions (e.g. `isNegativeEnd` for `HcalDigiID` or `idFromIndex` for `HcalElectronicsID`) 

I haven't been able to get the `__str__` function to work from the `<<` operators that we have defined. It produces a silly amount of template errors.   
  
Thoughts on this approach? I'm mostly familiar with the Hcal-related IDs so if there is something special you would want to have for the others, let me know. 

Here's an example of what the boilerplate looks like
https://github.com/LDMX-Software/ldmx-sw/blob/iss1048-detectorID-bindings/DetDescr/src/DetDescr/DetectorIDBindings.cxx

**Comment by omar-moreno** [comment]
@EinarElen This seems like a reasonable approach. Go for it :)

**Comment by EinarElen** [comment]
Ok, I now have a version that makes all of the IDs accessible from python. You can see it over here https://github.com/LDMX-Software/ldmx-sw/blob/iss1048-detectorID-bindings/DetDescr/src/DetDescr/DetectorIDBindings.cxx

I also add the necessary CMake scaffolding to the DetDescr subdirectory. I went for making bindings an optional and off by default feature, so things will still compile with containers that don't have boost python installed. I don't know if we want the CMake code in here or if you would want to move it elsewhere. It kind of makes the script a bit long. 

For the detector bindings, I've added some docstrings to most of the functions and classes in there. It does make the code a bit annoying to read through though, so I'm not entirely certain how desireable it is. Plus there is of course the obvious risk of the docstrings becoming outdated. 

To try it, you would just have to use `ldmx use dev iss41-boost-python` and configure with the `-DBUILD_DETECTORID_BINDINGS=ON` flag. You should then be able to `import libDetDescr` from a `ldmx python3` session. 

Note: I haven't gotten the functions that take a `std::pair` as a parameter to work yet. They compile but you can't actually use them from python. It should be possible to fix though. I also took the liberty of updating some minor copy/paste errors in the comments when I ran into them
