### ISSUE TITLE
Patch to Electronics ID deduction

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1053]
Following discussion with @mrsolt .

- Each HGC ROC has two "halves" that act almost independently and each of these halves produce their own data packets via their own link.
- Confusingly, the chip numbers the channels on it continuously across the two halves. Generally, the "lower" half (channels 0-35, on the board numbered 1 through 35) is given the link number (2 * ROC ID) and the "upper" half (channels 36-71. on the board numbered 36 through 71) is given the link number (2* ROC ID + 1). (Notice that the lower half has labels on the board printed incorrectly.)
- The HGC ROC v2 (A and B) have a common mode channel in both chip halves that is "inserted" into the readout at channel 19 (with respect to the channel number inside each half).
- Currently, the decoding skips channel 19 (the common mode channel) and does not include it in the output set of samples; however, it does not shift the channels numbers above 19 down by one in order to align with the numbers on the chip.
Even more confusingly, the chip inserts an extra header at "channel" index 0 so all of the channel numbers during decoding are shifted by one.
- All of this leads to the following (funky) formula for getting the channel number as listed on the chip (`chip_channel`) from the link and channel numbers decoded (`daq_channel`):
```cpp
chip_channel = (link%2)*36 + daq_channel - (daq_channel > 19)*1 - 1
roc_id = link / 2 // integer division
```

Currently, our electronics IDs use `link` and and `daq_channel` but from a connections perspective, the `roc_id` and `chip_channel` are more understandable. Switching to using `roc_id` and `chip_channel` in the electronics IDs will be more sustainable in the future.

Pulled from reading and rereading the [dataformats documentation](https://ldmx-software.github.io/pflib/hgcroc_dataformats.pdf), looking at the [1902_Schema.pdf](https://github.com/LDMX-Software/Hcal/files/8353190/1902_Schema.pdf) (analog inputs on second page), and looking at our HGC ROC at UMN.

**Comment by tomeichlersmith** [comment]
Transferring this issue to ldmx-sw since it will require changes to `HcalElectronicsID`.

**Comment by jmmans** [comment]
Sorry, what?  If a link goes down, for example, it's down.  For unpacking purposes, the two half chips are independent.  I disagree with this proposal.

**Comment by jmmans** [comment]
Also, if this is related to HCAL, HCAL doesn't use several of the channels /anyway/ because it operates in sum-by-four mode for trigger primitives.  I would NOT redesign the software id on this basis.

**Comment by tomeichlersmith** [comment]
Where would the translation between the channel numbers listed physically on the board and the channel numbers as given in the independent links be done? Does the detector mapping need to already include this translation? Does the HcalDetectorMap loader perform this translation while reading?

Edit: I'm not opposed to keeping the electronics IDs the way they are currently, I'm just trying to make the system less error prone and I'm not sure how to do that.
