### ISSUE TITLE
shorthand to pass environment variables to container

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#1089]
**Is your feature request related to a problem? Please describe.**
There are use cases for passing an environment variable to the container. Examples include Geant4 specific stuff. 

**Describe the solution you'd like**
This is easy with docker: use `-e`. Right now this would mean tweaking the definition of `ldmx_run`. I'd like to be able to add variables just like I can add directories to mount and have that list passed under the hood when I run e.g. `ldmx fire`. I propose a new command `ldmx env` (or some other name) that works just like `ldmx mount` but for environment variables. 

**Describe alternatives you've considered**
Hacking `ldmx-env.sh` or using the entire docker run command explicitly. Not that great

**Comment by tomeichlersmith** [comment]
I like this solution and have been thinking about it for some time. Is this something you are interested in implementing? If not, I can work on it as well.

**Comment by bryngemark** [comment]
I'd be happy to give it a go! I'll look to `ldmx mount` for inspiration.
