### ISSUE TITLE
Scoring Planes around Recoil Tracker in v14

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1099]
**Describe the bug**
The scoring planes around the recoil tracker use the GDML variable `recoil_layer_pos` which is not defined in constants.gdml for the v14 detector. For now, they are just commented out since their truth-level information is almost perfectly replicated by the recoil sim tracker hits themselves for subsystems outside the tracker.

**To Fix**
Update the recoil scoring plane position variable calculation so that it does not rely on this deprecated variable.

**Comment by omar-moreno** [comment]
![image](https://user-images.githubusercontent.com/3708508/198729213-e96bd677-2641-4df2-ad7d-193d89c1d3b9.png)
