### ISSUE TITLE
TrigScint naming updates

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1102]
**Describe the bug**
In the simulation module, the updated TrigScint geometry renamed the collections that it produced. This is a logical update which unfortunately has the cascading effect of requiring updates to the downstream input/output collection names.

In order to get the validation samples running, I commented out the TrigScint digi pipelines and the TrigScint DQM. This is obviously not long term, but I need someone more familiar with the TS pipeline to do the cascading name updates. Basically, I would like some updates allowing us to undo everything in https://github.com/LDMX-Software/ldmx-sw/commit/faad25ceaa5575a7b2c12ff587a3684190e84b16 .

@awhitbeck @bryngemark Maybe one of you has time this week to do this update?

**Comment by bryngemark** [comment]
hi @tomeichlersmith, it's the default tag/up/down naming scheme you're talking about, right, or is there more in the validation workflow?

**Comment by tomeichlersmith** [comment]
Yea - I am pretty sure its

Tagger -> TaggerA
Down -> TaggerB
Up -> Up

But I just need y'all to make sure its that simple.

**Comment by bryngemark** [comment]
alright. i can take a look and push an update, if not today then definitely by then end of the week

**Comment by bryngemark** [comment]
It is actually 
Tagger -> TaggerB
Down -> TaggerA
Up -> Up

@awhitbeck, now's probably a good time to decide if this is the naming we want. I find it a little confusing tbh. 

The Down pad is the only one that has moved, from just downstream of the target to upstream of every other subdetector. 

I propose either, in a logic that associates the trigger pads to their nearest other detector components
Tagger -> Tagger
Down -> Beam
Up -> Up

or 
Down -> Pad1
Tagger -> Pad2 
Up -> Pad3

Thoughts?

**Comment by bryngemark** [comment]
Haha oh, no you are right Tom, it's Down-->TaggerB, which comes *before* TaggerA. Did I mention I find it confusing..?

**Comment by awhitbeck** [comment]
I am fine renaming things to be more generic, like Pad1, Pad2, Pad3.  Is this this fairly easy to fix in the python configuration files?

**Comment by bryngemark** [comment]
Yeah, I think this is a pretty easy fix. The python configs for sure are, I'll think for a bit about if we need to or should change anything in the gdmls too.

**Comment by tomeichlersmith** [comment]
We've been looking into this in more detail on slack and I'm copying my debug notes here for persistency.

We are not seeing _any_ TS hits in collections even after confirming that they are being attached. I am running the config copied below.

## Checks
- [x] Being attached to correct volumes :heavy_check_mark: The simulation prints out when it is attaching an SD to a LV and it is correct.
- [x] If the TrigScintSD::ProcessHits function is being called :x: put a printout at the top of it and it is never being called, this led me to add the `StepPrinter` to the simulation and I don't see the primary electron stepping through _any_ of the TS volumes.
- [ ] Overlap with Tracker - looking more likely, **the Tagger and Recoil SimHit collections are also empty**
- [ ] Overlap with target
- [ ] Transversely aligned with beam
- [ ] Longitudinally aligned with beam

## config.py
@awhitbeck and @bryngemark I removed the generator modifications because all they did was move the electron from starting at `z=-800` to `z=-700`.

```python
import math
from LDMX.Framework import ldmxcfg
from LDMX.SimCore import sim_example
p = sim_example.process()
p.maxEvents = 10
p.sequence[0].setDetector('ldmx-det-v14')
import LDMX.Ecal.EcalGeometry
import LDMX.Hcal.HcalGeometry

p.sequence[0].verbosity = 10
p.termLogLevel = 0

from LDMX.Biasing import util
p.sequence[0].actions = [ util.StepPrinter() ]
```

**Comment by tomeichlersmith** [comment]
@awhitbeck noticed that the z position of the target sim hits are at `-845` which is _not_ near 0. Looking for a _longitudinal_ shift placing the TrigScint volumes upstream of the beam starting vertex.

**Comment by awhitbeck** [comment]
There were some conflicts in the naming convention that was causing some weird behaviors.  I have fixed them in branch iss1102.  I checked that there are hit collection for all three of the TS modules and the target.  I have all retuned the beam parameters so that the beam goes through the center of all TS modules and the target.   Plots below show how close I got. 

![image](https://user-images.githubusercontent.com/4173436/197055627-676516c0-2ad7-43fe-94b8-f7a0454f4d1f.png)
![image](https://user-images.githubusercontent.com/4173436/197055654-11def72b-b3dd-4051-9ed8-a0ddd8566618.png)
![image](https://user-images.githubusercontent.com/4173436/197055667-7ff88b46-0e81-4582-b4ee-e3b73ce4faa1.png)
![image](https://user-images.githubusercontent.com/4173436/197055683-59aba7cb-6d15-43a0-a93c-1a2ad27753c0.png)

beam parameters are: 

```p.sequence[0].generators[0].position=[-44.,0.,-880.]
theta = math.radians(5.65)
p.sequence[0].generators[0].direction=[math.sin(theta),0.,math.cos(theta)]
p.sequence[0].generators[0].energy=4.
```

It would be helpful if someone could verify this is reproducible when they check out my branch.  

We just need to decide on a new naming convention.

**Comment by bryngemark** [comment]
thanks @awhitbeck. if you start a PR, either of us can commit the name changes. i can do it after trying running sim+digi with your branch to verify, as you requested.

@tomeichlersmith, @omar-moreno, is the angle change (4.5 --> 5.65), needed when we move the beam starting point back, already included in default generator examples?

**Comment by tomeichlersmith** [comment]
The angle change is not in SimCore, I will make a patch release of SimCore for that reason.

**Comment by awhitbeck** [comment]
@tomeichlersmith I referenced an update to `SimCore` in my PR (#1107).  I also missed the position of the beam in my comment above; the angle and the starting position are critical.  Let me copy that information here, just to be sure: 

```
p.sequence[0].generators[0].position=[-44.,0.,-880.]
theta = math.radians(5.65)
p.sequence[0].generators[0].direction=[math.sin(theta),0.,math.cos(theta)]
p.sequence[0].generators[0].energy=4.
```
