### ISSUE TITLE
DR Geometry Validation

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1106]
This (similar to #1074 ) is a tracking issue, meaning it is meant to keep our various discussions organized.

**Each of the four subsystems is expected to do their own validation.** You are encouraged to create your own subsystem-specific issue and comment that link here. This issue is attempting to keep track of known bugs (:bug:) and changes (:zap:) that are related to each subsystem. 

- :bug: means it should be fixed before moving forward
- :zap: means it is understood as a physical change in the geometry and we are ok with that

A :bug: can turn into a :zap: if investigation shows that the difference is due to a physical change that we want to keep instead of a bug that needs to be fixed.

I am @-ing people who I know are related to that subsystem. Feel free to bring in others that are associated and will be working on validation.

If you make an issue related to validation, please **mark it with the v3.2.0 milestone** so it is included in our to-do list before making the full release.

## TrigScint
@awhitbeck @bryngemark @rodwyer100 

- :bug: #1102 
- :bug: #1104 

## Ecal
@tomeichlersmith @vdutta @AminaJLi @aechavez 

- :zap: bug in EcalGeometry (formerly EcalHexReadout) was only including the zero'th layer in total isolated energy calculations (not fixed by #1079)
- :bug: The total energy is peaking at ~3/5 the beam energy (probably due to change in silicon thickness) :heavy_check_mark: 
- #1112 
- https://github.com/LDMX-Software/Ecal/issues/43
- #1116 patched the 3/5 energy issue ecal reco was seeing (as well as moved noise handling to conditions)
- :zap: The number of hits is shifting down (from v12 to v14), the shower is thinning longitudinally, and thickening transversely which is due to the increased material between the sensitive layers (both air/light and absorber).
- https://github.com/LDMX-Software/ldmx-sw/issues/1123

## Hcal
@cmantill @EinarElen 

- :bug: https://github.com/LDMX-Software/ldmx-sw/issues/1109
- https://github.com/LDMX-Software/SimCore/pull/78
- #1132 

## Tracker
@omar-moreno @pbutti 

- :bug: #1099 
- :bug: TrackerSD not picking up the newly named volumes :heavy_check_mark: resolved with d043da5c7695902eede8691aae377b42554dbcb4

**Comment by bryngemark** [comment]
Should we close this issue now that all its corresponding items have been checked off and release v3.2.0 shipped? (@tomeichlersmith if you want to wait for it to actually be successfully built that's of course fine.)

**Comment by tomeichlersmith** [comment]
Yep, you're right.
