### ISSUE TITLE
Hcal geometry condition updates + refactoring

### ISSUE THREAD

**Issue by EinarElen** [LDMXAnalysis/ldmx-sw#1117]
Given the new and more complicated hcal geometry, there are more things we want to be able to ask the geometry condition. I want to take the opportunity when adding these to also try and clean things up in there a bit. @ehrlich-uva feel free to suggest other things you might need below

- [ ] Scintillator bar length from HcalID 
  - [x] Added parameter for v14
  - [x] Added parameter for prototype-geometries
  - [ ] Added parameter for v13 
   Not done yet, not sure about what the correct lengths for the side hcal should be here. Took 3.1 m for back hcal, but that might be wrong? @cmantill do you have any input here?
- ~Scintillator bar orientation from HcalID (no longer only relevant for the back hcal...)~ Not dealing with right now
- [x] Remove hacky code to handle v<14 geometries now that we have list[list]-parameters

**Comment by EinarElen** [comment]
For the scintillator bar orientation, I'm thinking maybe we can get away with not handling that yet. Currently, only the v14 geometry has a side-hcal which is relevant for Ralf's scintillation simulation so... We can survive with handling it there

**Comment by ehrlich-uva** [comment]
Is there a function that returns the version number of the geometry? If so, we can use some if/thens to use the older HcalDigitization methods for older geometry versions.

**Comment by EinarElen** [comment]
There isn't currently, but i still think it would be valuable to have two distinct digiproducers and in that case we maybe wouldn't need it

**Comment by ehrlich-uva** [comment]
Yes, we can keep both digiproducers.

**Comment by EinarElen** [comment]
I noticed now that I had forgotten to add the original feature that this issue was about :facepalm:. I added all the parts to the python config but no way of accessing them from the HcalGeometry objects. I'll add and test them ASAP, but this shouldn't make a difference w.r.t. the validation tests.
