### ISSUE TITLE
Move from 50 to 48 bars per TS array 

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#1126]
**Describe the bug**
For historical reasons, we've had 50 bars in the TS simulation, but we have long ago agreed that the numerology of 48 bars is superior. With the new geometry, time to make the move.

**Desired behavior**
24 bars per layer instead of 25 

**Additional context**
Keeping track of this here:
https://github.com/LDMX-Software/TrigScint/issues/48
but wanted an issue in this repo too so I can add it to milestone 3.2.0

**Comment by awhitbeck** [comment]
I agree, now is the time to do this. We should increase to the width of the bars by 0.05 mm, though.  Otherwise we won't cover the whole beam spot.
