### ISSUE TITLE
Event library is not created

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#1142]
All classes in the Event subdirectory are being skipped.  This requires changes to the CMake configuration.

**Comment by pbutti** [comment]
@tomeichlersmith Just so you are aware of the ongoing issue

**Comment by tomeichlersmith** [comment]
Y'all need to add the Tracking submodule to the other submodules that have Event libraries built.

https://github.com/LDMX-Software/ldmx-sw/blob/9537123974e3ab06be880e9fb9e2c29dea5b3329/CMakeLists.txt#L65-L73
