### ISSUE TITLE
Implement a Tagger hit filter

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#1147]
Implement a filter that will abort an event if a specified number of layers are not hit by the incident electron.  This filter is needed to study the impacts of off-energy electrons.

**Comment by tvami** [comment]
This exists now
https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Biasing/src/Biasing/TaggerHitFilter.cxx
closing this issue
