### ISSUE TITLE
TS Scoring Planes are not being attached

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1149]
**Describe the bug**
Running on current `trunk` (which is v3.2.1 + updated gold histograms) with high verbosity, we see in the basic simulation that there is no line for `Attaching trigscint_sp` to any of the TS scoring plane logical volumes.

**To Reproduce**
1. Build trunk and install it
2. Run basic: `ldmx fire ldmx-sw/SimCore/test/basic.py`
3. See the `sp_trigScint_PV` in the `ParallelWorld` printouts but no trig scint scoring plane SDs in the `DetectorConstruction` printouts.

**Desired behavior**
The scoring plane SDs are attached to the trig scint logical volumes as expected.

**Additional Context**
Expanded from discussion starting with https://github.com/LDMX-Software/ldmx-sw/pull/1121#issuecomment-1408734768

Possible fix within SimCore: https://github.com/LDMX-Software/SimCore/pull/87

**Comment by tomeichlersmith** [comment]
@bryngemark can you double check that my patch in SimCore works?

```
cd ldmx-sw
git fetch
git checkout trunk
git pull
cd SimCore
git fetch
git checkout patch-1104
cd ..
ldmx clean src
git submodule update --recursive --init
ldmx cmake -B build -S .
cd build
ldmx make install
ldmx fire ../SimCore/test/basic.py
```

**Comment by bryngemark** [comment]
ok i finally had a minute (an hour) for this.

running the indicated config i see:
```
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
[ ParallelWorld ]: Adding : sp_trigScint_PV to parallel world.
```

but the collection `TrigscintScoringPlaneHits_test` is (still) empty. All the other collections (including TS simhits and other scoring plane collections) are non-empty.

**Comment by bryngemark** [comment]
from the above it doesn't look like the capitalization is working. i.e. the Scint is still capitalized in the collection name but not in the sp name.

**Comment by bryngemark** [comment]
oh nevermind. the order of submodule operations above obviously undoes the checkout of the patch. checked it out again and rebuilt. now the collection is there :)

**Comment by tomeichlersmith** [comment]
oh good :) I was worried that I had totally missed it

Please "approve" the SimCore PR if/when you think it is ready: https://github.com/LDMX-Software/SimCore/pull/87
