### ISSUE TITLE
An 8 GeV version of v14 detector geometry 

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#1155]
It would be great to get going on some 8 GeV samples that we can compare apples-to-apples to the latest and greatest 4 GeV samples.

**Describe the solution you'd like**
The tagger tracker and TS upstream pads need to move to be aligned with the 8 GeV beam which has different rigidity.

**Describe alternatives you've considered**
ehh

**Additional context**
If there is a simple calculation to fix this, whoever has it, please add it to the issue :)

**Comment by tomeichlersmith** [comment]
This is also something I've wanted to have for an 8GeV EaT analysis! My general thoughts are to expand our current naming scheme to include the expected beam energy.

The detector-name would then be `ldmx-<detname>-v<version_number>-<beam_energy>` for example
`ldmx-det-v14-8GeV` would be this new detector. Any detector _without_ a `-<beam_energy>` suffix would be assumed to be for 4GeV _or_ whose design does not depend on the beam energy (like the test beam `hcal-prototype` geometry). This would then require re-naming some of the other detectors which already have a suffix.
- `ldmx-det-v9-ti-target` -> `ldmx-ti-target-v9`
- `ldmx-det-v12-lyso` -> `ldmx-lyso-v12`

I can also write up a README for the Detectors/data directory describing this scheme so future users know what we are doing and how we are trying to stay organized.

**Comment by EinarElen** [comment]
Sounds ressonable to my mind. If we are working on making changes to the detector geometries, one thing that has been on my wishlist for a while and which tends to trap newcommers would be to make the build system better at recognizing changes to the geometry. 

Currently, if I make changes to a gdml file and do make install, most of the time cmake won't notice that anything has changed so the installed gdml files won't change. What beginners tend to do is to go in and try and make the changes in the install directory instead. This works, untill you need to recompile which will overwrite what you have in the install directory. 

I think what's happening is that cmake copies the gdml sources to the build directory when we configure and then it uses whatever it copied as the source when installing


Also, if we are changing the naming schemes we should make sure that all the detectors_valid stuff in the geometry configurations are still matching.
