### ISSUE TITLE
Configurable EventProcessor System

### ISSUE THREAD

**Issue by jmmans** [LDMXAnalysis/ldmx-sw#118]
Based on the development in iss113:

Update the event processor core by adding a Framework package which allows the set of Processors to be configured dynamically.  

Adjust the class heirarchy so that EventImpl is a subclass of Event.

Introduce Analyzer and Producer event Processor types.

**Comment by JeremyMcCormick** [comment]
I'll close this as this issue will be resolved by PR #122.  Further comments/changes will be managed from the PR page.
