### ISSUE TITLE
Pull standalone G4 LYSO geometry into an LDMX gdml 

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#1226]
**Is your feature request related to a problem? Please describe.**
See #1225.  

**Describe the solution you'd like**
An alternative geometry where the current (W) target is replaced by a segmented LYSO bar active target geometry.

**Describe alternatives you've considered**
N/A

**Additional context**
Please ask @joyang8caltech for his Geant4 implementation of the geometry, and details of any changes to positions of other detector systems.

**Comment by bryngemark** [comment]
@tvami i guess this is a double for your issue #1283 , if we do need the same for 4 gev then that's not a hard change to make to the upstream TS and tracker layers.

**Comment by tvami** [comment]
> we do need the same for 4 gev then that's not a hard change

That's indeed not hard!

Is it realistic to have LYSO by the time we get 4 GeV beam? i.e. 2025 summer? If yes, should we then have it in the reduced LDMX-geometry too (a v2 version for that)?

**Comment by bryngemark** [comment]
there is a prototype already, and there will be S30XL test beam before, so it's not at all unthinkable. look at the CERN testbeam geometry for how we included LYSO that time around: as one of the two TS layers.
