### ISSUE TITLE
Strange bug in SampleValidation.cxx

### ISSUE THREAD

**Issue by jpasc27** [LDMXAnalysis/ldmx-sw#1239]
**Describe the bug**
The `hard_thresh` variable in **SampleValidation.cxx** of the DQM submodule is always printing out as 0. This happens both when it is calculated with non-zero values then immediately printed out, and when it is defined outside of a loop as a non-zero value and then printed out. 

**To Reproduce**
1. Ensure that your local version of `ldmx-sw` is up-to-date by doing `git pull` and then `git submodule update`.
2. Create an analysis config file, `test_config.py.` A screenshot of the config file I use for this analysis is below.
3. You need to have a ROOT file to input to your analysis config file - for the purposes of this bug, it might be easiest to produce a small sample using an electron particle gun. If you don't want to do that, reach out to me (@jpasc27 ) and I can send you the ROOT file that I use when doing this analysis.
4. Add a few print statements to `$LDMX_BASE/ldmx-sw/DQM/src/DQM/SampleValidation.cxx` to see the value(s) of the `hard_thresh` variable at different points in the code. For example, I added three print statements - one right after the variable is defined on L24, another right after it is calculated in the first `for` loop on L39, and a third in the second `for` loop where it is used as a filter (just under L54).
5. After saving your changes, navigate to `$LDMX_BASE/ldmx-sw/build/`and type `ldmx make install` to rebuild `ldmx-sw` and incorporate your changes.
6. Run your new config file outside of `ldmx-sw` with `ldmx fire test_config.py <output_file.root> <input_file.root>`. Your print statements should appear in your terminal window.

**Desired behavior**
The `hard_thresh` variable should print out a non-zero rescaled value of the energy.

**Screenshots**
<img width="472" alt="Example Config" src="https://github.com/LDMX-Software/ldmx-sw/assets/83837176/67bc4950-a752-4b44-9f96-b371c82d5180">

**Environment:**
Output of `ldmx config`:
```
LDMX base directory: /sfs/qumulo/qhome/jlp4td/LDMX
uname: Linux udc-ba34-36 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
OSTYPE: linux-gnu
Bash version: 4.2.46(2)-release
Display Port: 
Container Mounts: /sfs/qumulo/qhome/jlp4td/LDMX
Container Environments: 
Singularity Version: 3.7.1
Singularity File: /sfs/qumulo/qhome/jlp4td/LDMX/ldmx_dev_latest.sif
```

**Additional context**

**Comment by horohoo** [comment]
Attaching a few images of the start/end z position of the "hard brem" from the version of the code with the bug.


![endZ_hardbrem](https://github.com/LDMX-Software/ldmx-sw/assets/76532377/1a0ccd9b-d39c-4bd1-b2ab-21e79fd689a5)
![startZ_hardbrem](https://github.com/LDMX-Software/ldmx-sw/assets/76532377/66e47481-0176-47ad-af5c-12ef759aa21b)
