### ISSUE TITLE
Clang Format the Source Code

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1294]
A few of the submodules were making sure that the source code is clang-formatted in the Google style. Now that these submodules are not their own repos, the actions checking their style are not being run. Implementing an ldmx-sw wide format check would require everyone to format their code. `clang-format` is installed within the dev images, so formatting (and testing the format) can be done via `ldmx clang-format` both locally and in CI.

## For Example, SimCore
- https://github.com/LDMX-Software/ldmx-sw/blob/trunk/SimCore/.clang-format
- https://github.com/LDMX-Software/ldmx-sw/blob/trunk/SimCore/.github/workflows/format-check.yml
- https://github.com/LDMX-Software/ldmx-sw/blob/trunk/SimCore/.github/workflows/format-check.yml

Once format testing is done in the ldmx-sw actions (`.github`), then the directories `SimCore/.github`, `Hcal/.github`, `Framework/.github` can be removed. Other dangling `.clang-format` files can be removed as well.

**Comment by tvami** [comment]
Tracking package done in commit https://github.com/LDMX-Software/ldmx-sw/pull/1359/commits/062cf5a38ff31978a1ab2cd13ec7f696ea652fb2 in the PR https://github.com/LDMX-Software/ldmx-sw/pull/1359

**Comment by tomeichlersmith** [comment]
Might be helpful later...
```
git ls-tree -r HEAD --name-only | egrep '(\.h|\.cxx)$' > format.list
clang-format --style=Google -Werror --dry-run $(cat format.list)
```
