### ISSUE TITLE
Update DigitizationProcessor to use RandomNumberSeedService

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#1332]

**Comment by pbutti** [comment]
@omar-moreno Is this already implemented?

**Comment by omar-moreno** [comment]
I haven't implemented it. I'll do this as part of the detector load update.

**Comment by tomeichlersmith** [comment]
Notes for whomever does this in the future:

The seeding currently happens in `onProcessStart` at

https://github.com/LDMX-Software/ldmx-sw/blob/69f01ee406fa60518c9d0cf1e2ba551040aace8c/Tracking/src/Tracking/Reco/DigitizationProcessor.cxx#L56-L57

Instead, one should seed the generator in `onNewRun` which is after the conditions are configured and then one could
```cpp
const auto& rseed = getCondition<framework::RandomNumberSeedService>(
        framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
generator_.seed(rseed.getSeed("Tracking::DigitizationProcessor");
```

**Comment by tvami** [comment]
@tomeichlersmith you practically implemented this, is there any reason why you didnt PR it? Should I do it?

**Comment by tomeichlersmith** [comment]
No real reason, I vaguely remembering that this required an update to Framework so that conditions could be used in `onNewRun`, but I am confident this is fixed now.
