### ISSUE TITLE
Calorimeter digi Producers should create pure noise hits.

### ISSUE THREAD

**Issue by jmmans** [LDMXAnalysis/ldmx-sw#138]
The calorimeter digi code will currently add noise to existing Geant hits, but it needs to be extended to have a possibilty to create pure-noise hits on an appropriate statistical basis.

**Comment by awhitbeck** [comment]
this is addressed in PR #155

**Comment by omar-moreno** [comment]
The Ecal side of this issue was resolved by PR d0f6a441cd498268bdb1a0fc43d79572a3a10327.  @awhitbeck Are you still planning on working on the Hcal side of this?

**Comment by awhitbeck** [comment]
Yes, I have started working on this on this branch #poisson_noise.

**Comment by awhitbeck** [comment]
There is now a PR for this.

**Comment by omar-moreno** [comment]
This was resolved by PR #462
