### ISSUE TITLE
Ratio inset for plots in DQM Validation module

### ISSUE THREAD

**Issue by tvami** [LDMXAnalysis/ldmx-sw#1382]
**Is your feature request related to a problem? Please describe.**

Right now the `Validation` module offers to overlay 1D histograms.

**Describe the solution you'd like**

I believe it would be super useful to automatically generate a ratio plot in the bottom of the overlaid plot to show the differences.

**Describe alternatives you've considered**

One could do this outside of the `Validation` module in a private script, but wouldnt it be easier to do this once and have it in ldmx-sw?

**Comment by tvami** [comment]
Talked with Pritam privately and he agreed to have a look at this.

**Comment by tomeichlersmith** [comment]
I've done this so many times, here is the matplotlib code to do a raw/ratio plot.
```python
fig, (raw, ratio) = plt.subplots(
    nrows = 2,
    sharex = 'col',
    height_ratios = [2, 1], # height of raw panel relative to ratio panel
    gridspec_kw = dict(
        hspace = 0.05 # separation between panels, can be zero to overlap axis lines
    )
)

raw.hist(..., label='One')
raw.hist(..., label='Two')
raw.set_ylabel('Events')
raw.legend()

ratio.plot(one/two)
ratio.set_ylabel('Ratio')
ratio.set_xlabel('X Label / Units')

fig.savefig('filename.png', bbox_inches='tight')
fig.close() # only helpful in scripts like Validation where we want to cleanup figures that are done
```

**Comment by tvami** [comment]
Nice! I think what I'd like is to have the ratio inserted in the bottom of the canvas just below the main plot.
An example:
![Screenshot 2024-08-21 at 07 37 33](https://github.com/user-attachments/assets/3f3fa03f-de8b-4354-9f6d-f2eecde7cce6)

**Comment by tomeichlersmith** [comment]
That is what the above code does. `subplots` creates two "axes" in a grid within the "figure".

**Vocab Change**

matplotlib | ROOT
---|---
figure | TCanvas
axes | TPad
axis | TAxis

The code above is basically following [this guide](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subplots_demo.html#stacking-subplots-in-one-direction) but with some extra parameters I've learned while tuning the plots to be closer to what we want.

**Comment by tvami** [comment]
Ahh perfect, I didnt read it carefully! Will you PR it @tomeichlersmith ?

**Comment by tomeichlersmith** [comment]
Got a draft on the attached branch :+1: not sure when I'll get a chance to test it

**Comment by tvami** [comment]
I can give a try to testing, do you wanna open a draft PR?
