### ISSUE TITLE
Fieldmap offset is incorrect.

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#156]
Currently, the field is offset by -10 cm.  Instead the field should be offset by -40 cm.

**Comment by omar-moreno** [comment]
Attached is a comparison between the old fieldmap with the -100 mm offset and the new one with the -400 mm offset. 

![20170204_fieldmap_comparisons](https://cloud.githubusercontent.com/assets/3708508/22624425/c7e5f22e-eb30-11e6-80cd-75502f2e8632.png)

**Comment by JeremyMcCormick** [comment]
This should be resolved now with PR #157 which was merged.
