### ISSUE TITLE
Change include guard format.

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#21]
Use header guard format:

[dir]_[class]_H_

e.g.

EVENT_SIMTRACKER_HIT_

**Comment by JeremyMcCormick** [comment]
I think we should leave this alone for now.  There's not a compelling reason to change it.

**Comment by omar-moreno** [comment]
This issue has been resolved as of commit 8e006b005ec0dacf7b57070707dc9efc4b794b8b.  Style was changed to follow C++ core guidelines: 
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md
