### ISSUE TITLE
Add scoring planes to Geant4 simulation

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#241]

**Comment by JeremyMcCormick** [comment]
Possible we can use parallel world definition for this:

https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch04s07.html

We can look into defining the parallel world in a separate GDML file.

**Comment by omar-moreno** [comment]
This issue was resolved by PR 44b98c385ec81d649d2ccb589610b98b6dcc2fdc.
