### ISSUE TITLE
Ctrl+C ignored when running ldmx-app

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#242]
There is a minor bug where Ctrl+C does not shutdown and kill ldmx-app when it is running the recon in the terminal.  Not sure if the signal is being caught, but this should actually close down the app instead of being ignored.

**Comment by omar-moreno** [comment]
This issue was fixed by commit b86a0b7bbcd1039d510e7d265798ba9289910c0b.
