### ISSUE TITLE
Extend GDML parser so it can load referenced module files from relative path

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#250]
For instance, if the detector is loaded from '/work/detectors/ldmx-det/detector.gdml' then the parser should looked in '/work/detectors/ldmx-det/' for referenced module files, not just in the current working dir.

**Comment by JeremyMcCormick** [comment]
This is probably a lot of work.  It is a nice to have so I will close for now.

**Comment by omar-moreno** [comment]
​I would like to leave it open otherwise it's something that we will forget
about.  If you don't have time to fix it, I will.​

**Comment by JeremyMcCormick** [comment]
I will make it read from the detector data directory on the #134 branch.  The behavior described here is probably not needed then.
