### ISSUE TITLE
Ability to select only a subset of events for recording to the output file

### ISSUE THREAD

**Issue by jmmans** [LDMXAnalysis/ldmx-sw#254]
Add the ability for EventProcessor modules to indicate if a given event should be written to the file or not.

In the CMS framework, this is done by a new subclass of EventProcessor, the "Filter" which is also used in the software trigger.  For this to work, we'd need to reconsider the event processing from being a single linear sequence to being a set of multiple parallel sequences -- basically a tree of event processors.  I think this might be overkill/inappropriate for this purpose.

Instead, I propose to add to the EventProcessor a call which can be made to mark that the given event should or should not be kept.  Then, the framework python can contain the information as to which event processors should be consulted (and whether to apply an "OR" or "AND" logic between them).

**Comment by omar-moreno** [comment]
This was resolved by PR 7dbb94d0cb8b148d7bf3e9841d6172568f505030.
