### ISSUE TITLE
Illegal gun parameter error when using Geant4 10.03

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#277]
When I build ldmx-sw against Geant4 10.03 and try to generate some events, I get the following error:

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : Run0201
      issued by : G4VModularPhysicsList::RegisterPhysics
Geant4 kernel is not PreInit state : Method ignored.
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

parameter value (e-) is not listed in the candidate List.
***** Illegal parameter (0) </gun/particle e-> *****

**Comment by JeremyMcCormick** [comment]
The ldmx-sim initialization code needs to be rearranged for Geant4 10.3 and this is already covered by issue #266..
