### ISSUE TITLE
Fix broken macros.

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#278]
Several of the macros in the directory SimApplication/data/g4macros/ are unusable because they are missing commands.  They need to be updated so they can be used to generate valid samples.

**Comment by JeremyMcCormick** [comment]
Some of them were just intended as snippets to provide examples or macros that you could call with `/control/execute` in an interaction session, but if you want them to generally provide a full job then they can be changed.

Can you list here which ones you want updated?

**Comment by JeremyMcCormick** [comment]
Resolved by PR #374.
