### ISSUE TITLE
Seg fault when setting endpoint momentum in Trajectory

### ISSUE THREAD

**Issue by ASPatterson** [LDMXAnalysis/ldmx-sw#282]
The line
[https://github.com/LDMXAnalysis/ldmx-sw/blob/master/SimApplication/include/SimApplication/Trajectory.h#L190](https://github.com/LDMXAnalysis/ldmx-sw/blob/master/SimApplication/include/SimApplication/Trajectory.h#L190)
is causing a segfault in latest master. It happens to be receiving 0,0,0, but these values worked previously for other tracks. A getX() call on this data member also causes a segfault. Macro is:

```
/persistency/gdml/read detector.gdml
/run/initialize
/random/setSeeds 9644 598
/ldmx/plugins/load PhotonuclearXsecBiasingPlugin
/ldmx/plugins/PhotonuclearXsecBiasingPlugin/xsecFactor 1000.
/gun/particle e-
/gun/energy 4 GeV
/gun/position 0. 0. -0.55 mm
/gun/direction 0. 0. 4.0 GeV
/ldmx/persistency/root/verbose 2
/ldmx/persistency/root/file photonuc_biasing_test.root
/ldmx/plugins/load EventPrintPlugin
/ldmx/plugins/EventPrintPlugin/modulus 1000
/ldmx/plugins/load TargetBremFilter libBiasing.so
#/ldmx/plugins/load EcalProcessFilter libBiasing.so
/run/beamOn 100
```

The stack trace, after my bit of cout debugging (aTrack pointer, px, py, pz)
<pre>
###atrack 0x81e82f0
 ### in setEndPointMomentum: 0x81e82f0
 ### in setEndPointMomentum before endPointMomentum: 0x81e82f0 0 0 0

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f9f1147682e in waitpid () from /lib64/libc.so.6
#1  0x00007f9f11408479 in do_system () from /lib64/libc.so.6
#2  0x00007f9f1c2083af in TUnixSystem::StackTrace() () at /nfs/slac/g/ldmx/software/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:2324
#3  0x00007f9f1c20a0bc in TUnixSystem::DispatchSignals(ESignals) () at /nfs/slac/g/ldmx/software/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:3562
#4  <signal handler called>
#5  0x00007f9f18197ec8 in CLHEP::Hep3Vector::getX() const () from /nfs/slac/g/ldmx/users/ocolegro/forAlex/ldmx-sw/ldmx-sw-install/lib/libSimApplication.so
#6  0x00007f9f181981ff in ldmx::Trajectory::setEndPointMomentum(G4Track const*) () from /nfs/slac/g/ldmx/users/ocolegro/forAlex/ldmx-sw/ldmx-sw-install/lib/libSimApplication.so
#7  0x00007f9f18197a49 in ldmx::UserTrackingAction::PostUserTrackingAction(G4Track const*) () from /nfs/slac/g/ldmx/users/ocolegro/forAlex/ldmx-sw/ldmx-sw-install/lib/libSimApplication.so
#8  0x00007f9f15c06b85 in G4TrackingManager::ProcessOneTrack(G4Track*) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/tracking/src/G4TrackingManager.cc:140
#9  0x00007f9f15e3a221 in G4EventManager::DoProcessing(G4Event*) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/event/src/G4EventManager.cc:184
#10 0x00007f9f160c4947 in G4RunManager::ProcessOneEvent(int) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/run/src/G4RunManager.cc:399
#11 0x00007f9f160c32b3 in G4RunManager::DoEventLoop(int, char const*, int) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/run/src/G4RunManager.cc:367
#12 0x00007f9f160c30ae in G4RunManager::BeamOn(int, char const*, int) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/run/src/G4RunManager.cc:273
#13 0x00007f9f160dc1b3 in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/run/src/G4RunMessenger.cc:376
#14 0x00007f9f12668c45 in G4UIcommand::DoIt(G4String) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UIcommand.cc:230
#15 0x00007f9f12680ac8 in G4UImanager::ApplyCommand(char const*) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UImanager.cc:523
#16 0x00007f9f12659637 in G4UIbatch::ExecCommand(G4String const&) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UIbatch.cc:170
#17 0x00007f9f1265ac5b in G4UIbatch::SessionStart() () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UIbatch.cc:215
#18 0x00007f9f1267bdf3 in G4UImanager::ExecuteMacroFile(char const*) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UImanager.cc:296
#19 0x00007f9f12672049 in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UIcontrolMessenger.cc:313
#20 0x00007f9f12668c45 in G4UIcommand::DoIt(G4String) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UIcommand.cc:230
#21 0x00007f9f12680ac8 in G4UImanager::ApplyCommand(char const*) () at /nfs/slac/g/ldmx/software/geant4/rhel6-64/geant4.10.02.p02/source/intercoms/src/G4UImanager.cc:523
#22 0x00007f9f1818ce17 in ldmx::SimApplication::run(int, char**) () from /nfs/slac/g/ldmx/users/ocolegro/forAlex/ldmx-sw/ldmx-sw-install/lib/libSimApplication.so
#23 0x00000000004010c0 in main ()
===========================================================
</pre>

**Comment by JeremyMcCormick** [comment]
This should be fixed by PR #283.
