### ISSUE TITLE
Electro-nuclear Target Process Filtering.

### ISSUE THREAD

**Issue by arickman** [LDMXAnalysis/ldmx-sw#313]
Want to add a similar file to TargetProcessFilter.cxx in Biasing to filter electro-nuclear reactions rather than photo-nuclear ones in addition to modifying XsecBiasingOperator.cxx to allow for this new process biasing. Also want to add a new macro to actually bias EN reactions in simulation.

**Comment by omar-moreno** [comment]
This was resolved by PR #440 .
