### ISSUE TITLE
Move Recoil Information to Public in EcalVetoResult.h

### ISSUE THREAD

**Issue by GavinNiendorf** [LDMXAnalysis/ldmx-sw#332]
The recoil information is only made available in the private class of  EcalVetoResult.h, so the BDT cannot make use of any of the recoil information currently. See here: https://github.com/LDMXAnalysis/ldmx-sw/blob/master/Event/include/Event/EcalVetoResult.h

**Comment by omar-moreno** [comment]
This issue was resolved by commit b8fa0435849d631ed0c4388dea20c8be2187567b.
