### ISSUE TITLE
Fix ecalVetoProcessor clearing

### ISSUE THREAD

**Issue by ASPatterson** [LDMXAnalysis/ldmx-sw#345]
EcalVetoProcessor::Produce() never called result_.clear. As a result (heh), any variables not overwritten by result_.SetResult() (such as recoil P when this event has no SP hits) take on the values of the previous event. This leads to very undefined behavior during any analysis!

**Comment by omar-moreno** [comment]
This issue was resolved by e74cb67443ff9411b6ca9af7321e2dc72e041e73.
