### ISSUE TITLE
Sim output file is huge.

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#37]
A 50k event sim output file from 4 GeV electrons is ~13 gig which is about 260k per event.

**Comment by JeremyMcCormick** [comment]
**Collection and object sizes from the tree**

root [22] t->Print()                                                                                                                                         
******************************************************************************                                                                               
*Tree    :LDMX_Event: LDMX event tree                                        *                                                                               
*Entries :        1 : Total =           89943 bytes  File  Size =      18302 *                                                                               
*        :          : Tree compression factor =   1.00                       *                                                                               
******************************************************************************                                                                               
*Branch  :Event                                                              *                                                                               
*Entries :        1 : BranchElement (see below)                              *                                                                               
*............................................................................*                                                                               
*Br    0 :fUniqueID : UInt_t                                                 *                                                                               
*Entries :        1 : Total  Size=        764 bytes  File Size  =         86 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    1 :fBits     : UInt_t                                                 *                                                                               
*Entries :        1 : Total  Size=        756 bytes  File Size  =         94 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    2 :eventNumber_ : Int_t                                               *                                                                               
*Entries :        1 : Total  Size=        785 bytes  File Size  =         89 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    3 :run_      : Int_t                                                  *                                                                               
*Entries :        1 : Total  Size=        729 bytes  File Size  =         81 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    4 :timestamp_ : Int_t                                                 *                                                                               
*Entries :        1 : Total  Size=        771 bytes  File Size  =         87 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    5 :weight_   : Double_t                                               *                                                                               
*Entries :        1 : Total  Size=        758 bytes  File Size  =         88 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    6 :simParticles_ : Int_t simParticles__                               *                                                                               
*Entries :        1 : Total  Size=      16753 bytes  File Size  =         90 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    7 :simParticles_.fUniqueID : UInt_t fUniqueID[simParticles__]         *                                                                               
*Entries :        1 : Total  Size=        966 bytes  File Size  =        108 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    8 :simParticles_.fBits : UInt_t fBits[simParticles__]                 *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br    9 :simParticles_.energy_ : Double_t energy_[simParticles__]           *                                                                               
*Entries :        1 : Total  Size=        952 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   10 :simParticles_.pdg_ : Int_t pdg_[simParticles__]                    *                                                                               
*Entries :        1 : Total  Size=        931 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   11 :simParticles_.genStatus_ : Int_t genStatus_[simParticles__]        *                                                                               
*Entries :        1 : Total  Size=        973 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   12 :simParticles_.time_ : Float_t time_[simParticles__]                *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   13 :simParticles_.x_ : Float_t x_[simParticles__]                      *                                                                               
*Entries :        1 : Total  Size=        917 bytes  File Size  =        101 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   14 :simParticles_.y_ : Float_t y_[simParticles__]                      *                                                                               
*Entries :        1 : Total  Size=        917 bytes  File Size  =        101 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   15 :simParticles_.z_ : Float_t z_[simParticles__]                      *                                                                               
*Entries :        1 : Total  Size=        917 bytes  File Size  =        101 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   16 :simParticles_.endX_ : Float_t endX_[simParticles__]                *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   17 :simParticles_.endY_ : Float_t endY_[simParticles__]                *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   18 :simParticles_.endZ_ : Float_t endZ_[simParticles__]                *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   19 :simParticles_.px_ : Float_t px_[simParticles__]                    *                                                                               
*Entries :        1 : Total  Size=        924 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   20 :simParticles_.py_ : Float_t py_[simParticles__]                    *                                                                               
*Entries :        1 : Total  Size=        924 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   21 :simParticles_.pz_ : Float_t pz_[simParticles__]                    *                                                                               
*Entries :        1 : Total  Size=        924 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   22 :simParticles_.mass_ : Float_t mass_[simParticles__]                *                                                                               
*Entries :        1 : Total  Size=        938 bytes  File Size  =        104 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   23 :simParticles_.charge_ : Float_t charge_[simParticles__]            *                                                                               
*Entries :        1 : Total  Size=        952 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   24 :simParticles_.daughters_ : TRefArray* daughters_[simParticles__]   *                                                                               
*Entries :        1 : Total  Size=        973 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   25 :simParticles_.parents_ : TRefArray* parents_[simParticles__]       *                                                                               
*Entries :        1 : Total  Size=        959 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   26 :taggerSimHits_ : Int_t taggerSimHits__                             *                                                                               
*Entries :        1 : Total  Size=      12828 bytes  File Size  =         91 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   27 :taggerSimHits_.fUniqueID : UInt_t fUniqueID[taggerSimHits__]       *                                                                               
*Entries :        1 : Total  Size=        975 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   28 :taggerSimHits_.fBits : UInt_t fBits[taggerSimHits__]               *                                                                               
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   29 :taggerSimHits_.id_ : Int_t id_[taggerSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        933 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   30 :taggerSimHits_.layerID_ : Int_t layerID_[taggerSimHits__]          *                                                                               
*Entries :        1 : Total  Size=        968 bytes  File Size  =        108 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   31 :taggerSimHits_.edep_ : Float_t edep_[taggerSimHits__]              *                                                                               
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   32 :taggerSimHits_.time_ : Float_t time_[taggerSimHits__]              *                                                                               
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   33 :taggerSimHits_.px_ : Float_t px_[taggerSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        933 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   34 :taggerSimHits_.py_ : Float_t py_[taggerSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        933 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   35 :taggerSimHits_.pz_ : Float_t pz_[taggerSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        933 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   36 :taggerSimHits_.x_ : Float_t x_[taggerSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   37 :taggerSimHits_.y_ : Float_t y_[taggerSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   38 :taggerSimHits_.z_ : Float_t z_[taggerSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   39 :taggerSimHits_.pathLength_ : Float_t pathLength_[taggerSimHits__]  *                                                                               
*Entries :        1 : Total  Size=        989 bytes  File Size  =        111 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   40 :taggerSimHits_.simParticle_ : TRef simParticle_[taggerSimHits__]   *                                                                               
*Entries :        1 : Total  Size=        996 bytes  File Size  =        112 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   41 :recoilSimHits_ : Int_t recoilSimHits__                             *                                                                               
*Entries :        1 : Total  Size=      12892 bytes  File Size  =         91 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   42 :recoilSimHits_.fUniqueID : UInt_t fUniqueID[recoilSimHits__]       *                                                                               
*Entries :        1 : Total  Size=        983 bytes  File Size  =        113 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   43 :recoilSimHits_.fBits : UInt_t fBits[recoilSimHits__]               *                                                                               
*Entries :        1 : Total  Size=        955 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   44 :recoilSimHits_.id_ : Int_t id_[recoilSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        941 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   45 :recoilSimHits_.layerID_ : Int_t layerID_[recoilSimHits__]          *                                                                               
*Entries :        1 : Total  Size=        976 bytes  File Size  =        112 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   46 :recoilSimHits_.edep_ : Float_t edep_[recoilSimHits__]              *                                                                               
*Entries :        1 : Total  Size=        955 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   47 :recoilSimHits_.time_ : Float_t time_[recoilSimHits__]              *                                                                               
*Entries :        1 : Total  Size=        955 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   48 :recoilSimHits_.px_ : Float_t px_[recoilSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        941 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   49 :recoilSimHits_.py_ : Float_t py_[recoilSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        941 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   50 :recoilSimHits_.pz_ : Float_t pz_[recoilSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        941 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   51 :recoilSimHits_.x_ : Float_t x_[recoilSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        934 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   52 :recoilSimHits_.y_ : Float_t y_[recoilSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        934 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   53 :recoilSimHits_.z_ : Float_t z_[recoilSimHits__]                    *                                                                               
*Entries :        1 : Total  Size=        934 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   54 :recoilSimHits_.pathLength_ : Float_t pathLength_[recoilSimHits__]  *                                                                               
*Entries :        1 : Total  Size=        997 bytes  File Size  =        115 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   55 :recoilSimHits_.simParticle_ : TRef simParticle_[recoilSimHits__]   *                                                                               
*Entries :        1 : Total  Size=       1020 bytes  File Size  =        124 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   56 :ecalSimHits_ : Int_t ecalSimHits__                                 *                                                                               
*Entries :        1 : Total  Size=       8642 bytes  File Size  =         89 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   57 :ecalSimHits_.fUniqueID : UInt_t fUniqueID[ecalSimHits__]           *                                                                               
*Entries :        1 : Total  Size=        957 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   58 :ecalSimHits_.fBits : UInt_t fBits[ecalSimHits__]                   *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   59 :ecalSimHits_.id_ : Int_t id_[ecalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        915 bytes  File Size  =        101 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   60 :ecalSimHits_.edep_ : Float_t edep_[ecalSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   61 :ecalSimHits_.x_ : Float_t x_[ecalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   62 :ecalSimHits_.y_ : Float_t y_[ecalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   63 :ecalSimHits_.z_ : Float_t z_[ecalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   64 :ecalSimHits_.time_ : Float_t time_[ecalSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   65 :ecalSimHits_.simParticle_ : TRef simParticle_[ecalSimHits__]       *                                                                               
*Entries :        1 : Total  Size=        978 bytes  File Size  =        110 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   66 :hcalSimHits_ : Int_t hcalSimHits__                                 *                                                                               
*Entries :        1 : Total  Size=       8642 bytes  File Size  =         89 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   67 :hcalSimHits_.fUniqueID : UInt_t fUniqueID[hcalSimHits__]           *                                                                               
*Entries :        1 : Total  Size=        957 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   68 :hcalSimHits_.fBits : UInt_t fBits[hcalSimHits__]                   *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   69 :hcalSimHits_.id_ : Int_t id_[hcalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        915 bytes  File Size  =        101 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   70 :hcalSimHits_.edep_ : Float_t edep_[hcalSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   71 :hcalSimHits_.x_ : Float_t x_[hcalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   72 :hcalSimHits_.y_ : Float_t y_[hcalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   73 :hcalSimHits_.z_ : Float_t z_[hcalSimHits__]                        *                                                                               
*Entries :        1 : Total  Size=        908 bytes  File Size  =        100 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   74 :hcalSimHits_.time_ : Float_t time_[hcalSimHits__]                  *                                                                               
*Entries :        1 : Total  Size=        929 bytes  File Size  =        103 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   75 :hcalSimHits_.simParticle_ : TRef simParticle_[hcalSimHits__]       *                                                                               
*Entries :        1 : Total  Size=        978 bytes  File Size  =        110 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   76 :triggerPadSimHits_ : Int_t triggerPadSimHits__                     *                                                                               
*Entries :        1 : Total  Size=       9020 bytes  File Size  =         95 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   77 :triggerPadSimHits_.fUniqueID :                                     *                                                                               
*         | UInt_t fUniqueID[triggerPadSimHits__]                            *                                                                               
*Entries :        1 : Total  Size=       1011 bytes  File Size  =        113 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   78 :triggerPadSimHits_.fBits : UInt_t fBits[triggerPadSimHits__]       *                                                                               
*Entries :        1 : Total  Size=        983 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   79 :triggerPadSimHits_.id_ : Int_t id_[triggerPadSimHits__]            *                                                                               
*Entries :        1 : Total  Size=        969 bytes  File Size  =        107 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   80 :triggerPadSimHits_.edep_ : Float_t edep_[triggerPadSimHits__]      *                                                                               
*Entries :        1 : Total  Size=        983 bytes  File Size  =        109 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   81 :triggerPadSimHits_.x_ : Float_t x_[triggerPadSimHits__]            *                                                                               
*Entries :        1 : Total  Size=        962 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*                                                                               
*Br   82 :triggerPadSimHits_.y_ : Float_t y_[triggerPadSimHits__]            *                                                                               
*Entries :        1 : Total  Size=        962 bytes  File Size  =        106 *                                                                               
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *                                                                               
*............................................................................*
*Br   83 :triggerPadSimHits_.z_ : Float_t z_[triggerPadSimHits__]            *
*Entries :        1 : Total  Size=        962 bytes  File Size  =        106 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   84 :triggerPadSimHits_.time_ : Float_t time_[triggerPadSimHits__]      *
*Entries :        1 : Total  Size=        983 bytes  File Size  =        109 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   85 :triggerPadSimHits_.simParticle_ :                                  *
*         | TRef simParticle_[triggerPadSimHits__]                           *
*Entries :        1 : Total  Size=       1032 bytes  File Size  =        116 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   86 :targetSimHits_ : Int_t targetSimHits__                             *
*Entries :        1 : Total  Size=       8768 bytes  File Size  =         91 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   87 :targetSimHits_.fUniqueID : UInt_t fUniqueID[targetSimHits__]       *
*Entries :        1 : Total  Size=        975 bytes  File Size  =        109 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   88 :targetSimHits_.fBits : UInt_t fBits[targetSimHits__]               *
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   89 :targetSimHits_.id_ : Int_t id_[targetSimHits__]                    *
*Entries :        1 : Total  Size=        933 bytes  File Size  =        103 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   90 :targetSimHits_.edep_ : Float_t edep_[targetSimHits__]              *
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   91 :targetSimHits_.x_ : Float_t x_[targetSimHits__]                    *
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   92 :targetSimHits_.y_ : Float_t y_[targetSimHits__]                    *
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   93 :targetSimHits_.z_ : Float_t z_[targetSimHits__]                    *
*Entries :        1 : Total  Size=        926 bytes  File Size  =        102 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   94 :targetSimHits_.time_ : Float_t time_[targetSimHits__]              *
*Entries :        1 : Total  Size=        947 bytes  File Size  =        105 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br   95 :targetSimHits_.simParticle_ : TRef simParticle_[targetSimHits__]   *
*Entries :        1 : Total  Size=        996 bytes  File Size  =        112 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*

**Comment by JeremyMcCormick** [comment]
collection and object sizes from event

http://www.slac.stanford.edu/~jeremym/ldmx/root_tree_huge.txt

Single float field is 955 bytes, etc.

**Comment by JeremyMcCormick** [comment]
Created a [help thread in the ROOT forum](https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=22643).

**Comment by JeremyMcCormick** [comment]
Unfortunately, it looks like the events themselves have a reasonable size based on the number of objects in the collections.

There are about 890 ecal hits per event, so assuming a SimCalorimeterHit is ~60 bytes, this is 54k per event in just ecal hit data (uncompressed).  Total event size seems to be around 40k.

Probably we will need to reduce the number of cal hits by performing digitization in the simulation or some similar strategy.

**Comment by awhitbeck** [comment]
I can implement an ecal digi processor to at least try to access how much we can reduce the event size, if you think this will help.

**Comment by JeremyMcCormick** [comment]
@awhitbeck I think there is some other problem that is ballooning the files by 6-7 times what I would expect.  I calculated that event size should be about 40 kb with the ecal hits but even then 50k events would be ~2 gig but it comes out to ~14 gig or more.  So something is not right.

**Comment by omar-moreno** [comment]
@awhitbeck An Ecal digi processor would still be good to implement.  In the end, I don't think we want hundreds of Ecal hits per event.

**Comment by JeremyMcCormick** [comment]
This looks much better in the current master.  The Event object is immediately cleared after the Fill() is called on the tree.  This seemed to fix the memory leak that was causing this (maybe?).  I ran 10k events and the file size is 626M which is still pretty big but about 7x smaller than before so it is much more manageable now.
