### ISSUE TITLE
Updates to EcalDetectorID and EcalHit class

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#372]
- Change name to `EcalID`

- Fix wonky indentation in header file

- Change "module_position" to "module" (the value of this field is definitely not a position!)

- Add `getModule()` and `getCell()` accessors to `EcalHit` in Event module

**Comment by omar-moreno** [comment]
Before making changes to the EcalHit class, you should consult with the UCSB group first.  Specifically, you should have @ASPatterson take a look at them.
