### ISSUE TITLE
ECal Calibration and Trigger Skim

### ISSUE THREAD

**Issue by JHiltbrand** [LDMXAnalysis/ldmx-sw#386]
Corresponding branch will introduce layer weighting in the ECal digi producer for edep calibration and a trigger skim.

**Comment by JHiltbrand** [comment]
With current trigger skim config running on an ECal PN file (20 layer sum, Edep < 1.5 GeV):

290 MB -> 51 MB, 82.4% size reduction
11,429 events ->  1,520 events

**Comment by omar-moreno** [comment]
This issue was resolved by commit f87685ee7b7424c2551e7e7f86f062d4ec73a809.
