### ISSUE TITLE
libSimPlugins.so: undefined reference to ...

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#48]
The order of libraries passed to the linker matters. A library should be listed after specifying the objects that require it. 

http://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

This doesn't seem to cause issues on OSX but is a problem on most Linux distros.  The "MacroModule" needs to be changed in order to fix this.

**Comment by JeremyMcCormick** [comment]
How can I reproduce whatever error you are getting?

**Comment by JeremyMcCormick** [comment]
Okay, so we solved this one with defining the plugin's constructor in the header file.
