### ISSUE TITLE
Run simulation on v9 with ldmx-sw v2.3 (or later)

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#948]
**Describe the bug**
I have attempted running an 8 GeV beam with the `v9` detector. My config works fine for the `v12` detector, but with `v9` I get a seg fault:
```
0x00007f2c71cbb4d1 in ldmx::AuxInfoReader::createSensitiveDetector(G4String, std::vector<G4GDMLAuxStructType, std::allocator<G4GDMLAuxStructType> > const*) + 0x1511 from /usr/local/lib/libSimCore.so
 0x00007f2c71cbe32b in ldmx::AuxInfoReader::readGlobalAuxInfo() + 0x1eb from /usr/local/lib/libSimCore.so
 0x00007f2c71cc40a2 in ldmx::DetectorConstruction::Construct() + 0x22 from /usr/local/lib/libSimCore.so
 0x00007f2c70d27e4a in G4RunManager::InitializeGeometry() at /geant4/geant4/source/run/src/G4RunManager.cc:581 from /deps/geant4/lib/libG4run.so
 0x00007f2c70d27d79 in G4RunManager::Initialize() at /geant4/geant4/source/run/src/G4RunManager.cc:566 (discriminator 1) from /deps/geant4/lib/libG4run.so
 0x00007f2c71d17482 in ldmx::RunManager::Initialize() + 0x52 from /usr/local/lib/libSimCore.so
 0x00007f2c71d1d09c in ldmx::Simulator::onProcessStart() + 0x3c from /usr/local/lib/libSimCore.so
 0x00007f2c7b7241f6 in ldmx::Process::run() + 0xe6 from /usr/local//lib/libFramework.so
```

**To Reproduce**
Use the template simulation script in the LDCS repo [here](https://github.com/LDMX-Software/LDCS/blob/master/productionScripts/v2.3/ldmxjob-2.3.0_v9.py.tpl). 
1. change RUNNUMBER to an actual int
2. rename it to something without dots in the name before the actual .py file extension
3. run with `fire` using the docker production container `pro/v2.3.0` or a corresponding singularity image (or corresponding env...)

**Desired behavior**
It would be great to be able to run on other detectors than the current one!

**Environment:**
Docker container `pro/v2.3.0`

**Comment by omar-moreno** [comment]
An issue for this already exists.  Will close this one.
