### ISSUE TITLE
Tab Completion when interacting with container

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#966]
I just found out that you can [customize how your commands respond to tab-completion requests](https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial). This is pretty rad, and I want to do it. My idea is to have `ldmx` be **the** command with multiple sub-commands (kinda like how `docker` has multiple sub-commands). The command tree I'm thinking of implementing is

- `ldmx`
     - `list` : list tags for the input repo name
     - `clean` : remove all containers and container images on the local machine
     - `config` : print out configuration to stdout
     - `pull` : pull down input container image and set it to be used
     - `use` : use input container image and only pull down if it doesn't exist on local machine
     - `run` : Got to first argument and then run everything after it in the container (basically what the entry-point script does)
     - `fire <stuff>` : Equivalent to `run $(pwd) fire <stuff>`
     - `make <stuff>` : Equivalent to `run $(pwd) make <stuff>`
     - `cmake <stuff>` : Equivalent to `run $(pwd) cmake <stuff>`
     - (and so on with other ldmx-sw commands, I think I will be able to automate this to pick up all executables in the ldmx-sw install)

**Comment by bryngemark** [comment]
cool! would `ldmx mount` be a good idea? primarily for when you want to run on data from some input path.

**Comment by tomeichlersmith** [comment]
Great idea! I will look into it :+1:

**Comment by tomeichlersmith** [comment]
`ldmx mount` will be included, I've opened up a draft PR #970 to point out my progress. I still need to check that it works on `singularity` systems.
