### ISSUE TITLE
Make the number of earlier/later bunches used for pileup independent

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#968]
In the current implementation, out-of-time pileup is placed symmetrically in +/- _m_ bunches. This should be separately configurable (so place pileup in a random bunch from a continuum starting 3 bunches before, to 10 bunches after, or whatever). 

**Describe the solution**
I'm going to change the setup in the `OverlayProducer` such that two numbers are specified instead of one.

**Comment by GNiramay** [comment]
I was wondering, can we also specify a physical time range for the pileup? I mean, instead of setting +/- 4 bunches, can we specify +/- 100ns perhaps?

**Comment by bryngemark** [comment]
Hi @GNiramay, sorry, my github notifications have been ending up in spam lately :(

I think we do want to operate under the assumption that the beam will be bunched? That said, it is already possible to smear the time within a bunch (applies also to out-of-time bunches). I've set this smearing to a Gaussian distribution, but that could be tweaked/configurable if there is a use case for it. Any thoughts from @awhitbeck?
