### ISSUE TITLE
Improved realism of out-of-time pileup simulation

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#974]
Currently, out-of-time pileup is simulated by choosing a total number of interactions, and then a per-event time offset is calculated by uniform sampling of an interval given by `(-nEarlier, nLater)*bunchSpacing`.

**Improved method**
Given an interval of bunches to populate, the number of pileup events to plug in should be set, either as a fixed number, or, by sampling a Poisson distribution around a fixed µ, for each bunch. So we'd calculate the pileup event time shift in an outer loop over bunches to populate, rather than inside a loop over a total number of pileup events. In-time pileup is the special case when the loop reaches the sim event bunch, still respecting the same total number of interactions as in the out-of-time bunches.

**Additional features considered**
Right now we're putting pileup in bunches ` bunchNumber=[-nEarlier,-nEarlier+1,…,0,…,nLater]` (with pileup event times shifted by `bunchSpacing*bunchNumber` ns).
I'm also considering adding the flexibility to randomly shift the start and end bunch of the out-of-time bunch interval with respect to the "sim event", like so:
- sample a uniform distribution (0, _nBunches_) for a position _b_ which is the sim event (time = 0) position within the interval
- the sim event times aren't actually shifted (just adds a layer of complication and processing time)
- for all bunches with` bunchNumber=[-b, -b+1, …, 0, …, nBunches-b]`, add pileup and shift times as before 

**Additional context**
These improvements would come in really handy for early-beam simulations in time for the early-data workshop.

**Comment by tomeichlersmith** [comment]
Merged with PR #975 so I'm closing this. (@bryngemark Feel free to re-open if I'm missing something.)
